services:
  aziondb:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always

  azionapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - aziondb
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DB_URL: '${DB_URL}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      SECRET_JWT: '${SECRET_JWT}'
      ISSUER_NAME: '${ISSUER_NAME}'
      SECRET_MFA: '${SECRET_MFA}'
      OS: '${OS}'
      VIRUS_TOTAL_API_KEY: '${VIRUS_TOTAL_API_KEY}'
      GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID}'
      GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
      GOOGLE_REDIRECT_URI: '${GOOGLE_REDIRECT_URI}'
      SECRET_GOOGLE: '${SECRET_GOOGLE}'
    restart: always

#Prod only
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - azionapp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
