name: Create release from current tag

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get latest tag
        id: get_tag
        run: echo "CURRENT_TAG=$(git describe --tags $((git rev-list --tags --max-count=1))" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CURRENT_TAG }}
          release_name: Release ${{ env.CURRENT_TAG }}
          draft: false
          prerelease: false