name: Version generator

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # this is required to fetch all tags
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Get commit message or PR description
        id: get_info
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
            echo "INFO=$MESSAGE" >> $GITHUB_ENV
          else
            PR_DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} | jq -r .body)
            echo "INFO=$PR_DESCRIPTION" >> $GITHUB_ENV
          fi
      - name: Auto Versioning
        uses: Soumeh-zz/Auto-Versioning@v2.0
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          version-file-path: 'VERSION.txt'