name: Bump version and create release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          default_bump: patch
      - name: Print new tag
        run: echo "New tag is ${{ steps.tag_version.outputs.newTag }}"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.newTag }}
          release_name: Release ${{ needs.build.outputs.newTag }}
          draft: false
          prerelease: false